name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Test package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          python -m pip install --upgrade pip && pip install -r requirements.txt
          cp .travis/system.dic.test tests/resources/system.dic && cp .travis/user.dic.test tests/resources/user.dic && cp .travis/user2.dic.test tests/resources/user2.dic
          python -m unittest discover tests
